### ISSUE TITLE
Portainer Business

### ISSUE THREAD

**Issue by olaxe** [MikeJMcGuire/hass-portainer#3]
Hello,

Is it something doable to add the Business version since we can have access to it very easily with: [sign up for a 5 node free license](https://www.portainer.io/get-a-license)

I am using the Business version for upgrade and Git sync with docker-compose of stacks.

Thanks in advance,

**Comment by MikeJMcGuire** [comment]
Howdy - probably straight forward, unless the business version works quite differently. I'll have a look.

**Comment by olaxe** [comment]
Thanks for your feedback and your consideration

**Comment by MikeJMcGuire** [comment]
Added to the repository.
