### ISSUE TITLE
Won't Start anymore

### ISSUE THREAD

**Issue by BiasF** [MikeJMcGuire/hass-portainer#4]
Hi,

i always get the following error which prevent the Start of the portainer addon:

2023/07/19 08:40AM FTL github.com/portainer/portainer/api/cmd/portainer/main.go:65 > failed validating flags | error="Unable to locate Unix socket or named pipe"

**Comment by MikeJMcGuire** [comment]
Platform? HA config/version?

**Comment by RioLi08123** [comment]
@BiasF I have same issues but how to disable protected mode
